# -*- coding: utf-8 -*-
"""PROBLEM3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RLjBm769qB-EMxduzf3LcJrkvTiuGT5e
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
from scipy import signal
import matplotlib.pyplot as plt
from PIL import Image
# %matplotlib inline

# Commented out IPython magic to ensure Python compatibility.
import cv2
import numpy as np
from scipy import signal
import matplotlib.pyplot as plt
from PIL import Image
# %matplotlib inline

from google.colab import files
uploaded = files.upload()

IMAGE = cv2.imread("02Rice.png",0)
fig, aux = plt.subplots(figsize=(8,8))
aux.imshow(IMAGE,cmap="gray")

LAPLACIAN = cv2.Laplacian(IMAGE, cv2.CV_64F, ksize=5)
fig, aux = plt.subplots(figsize=(8,8))
aux.imshow(LAPLACIAN,cmap="gray")

SOBELX = cv2.Sobel(IMAGE, cv2.CV_64F, 1, 0, ksize =5)

fig, aux = plt.subplots(figsize = (8,8))
aux.imshow(SOBELX, cmap="gray")

SOBELY = cv2.Sobel(IMAGE, cv2.CV_64F, 0, 1, ksize =5)

fig, aux = plt.subplots(figsize = (8,8))
aux.imshow(SOBELY, cmap="gray")

CANNY = cv2.Canny(IMAGE, 50, 200)

fig, aux = plt.subplots(figsize = (8,8))
aux.imshow(CANNY, cmap="gray")

