# -*- coding: utf-8 -*-
"""TF_part1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kQzz0EoEDP94pwNQKU2hIMnowUSvSjMg
"""

import tensorflow as tf
print(tf.__version__)

import keras as ks
print(ks.__version__)

import numpy as np

a = np.array([5,3,8])
b = np.array([3,-1,2])
c = np.add(a,b)
print(c)

a1 = tf.constant([5,3,8])
b1 = tf.constant([3,-1,2])
c1 = tf.add(a1,b1)
print(c1)

x0 = tf.constant(3)
print(x0)
print(x0.shape)
print("----")

x1 = tf.constant([3,5,7])
print(x1)
print(x1.shape)
print("----")

x2 = tf.constant([[3,5,7],[4,6,8]])
print(x2)
print(x2.shape)
print("----")

x3 = tf.constant(  [ [ [3,5,7],[4,6,8]], [ [1,2,3], [4,5,6] ] ])
print(x3)
print(x3.shape)
print("----")



x1 = tf.constant([2,3,4])
print(x1.shape)

x2 = tf.stack([x1,x1])
print(x2.shape)

x3 = tf.stack([ x2, x2, x2, x2])
print(x3.shape)

x4 = tf.stack([x3,x3])
print(x4.shape)

print(x1)
print(x2)
print(x3)
print(x4)



x = tf.constant([[3,5,7],[4,6,8]])
print(x)

y = x[:,1]
print(y)

y1 = x[1,:]
print(y1)

y2 = x[1, 0:2]
print(y2)



y = tf.constant([[3,5,7],[4,6,8]])
print(y)
y1 = tf.reshape(y,[3,2])
print(y1)



print(y1)
y2 = tf.reshape(y,[3,2])[1,:]
print(y2)

