# -*- coding: utf-8 -*-
"""HW8_part3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SnPk3N52FYJY8tYHA3_aL5cPu78VOUC7
"""

import numpy as np
import scipy as sp
from numpy import array
from scipy.stats import entropy
from scipy.special import rel_entr, kl_div

# the base e of the logarithm

def ENTROPY_e(p) : 
    return np.sum(-p * np.log(p))

# the base 2 of the logarithm
# although we do mainly used the ENTROPY_e
# def ENTROPY_2(p) : 
#     return np.sum(-p * np.log(p)/ np.log(2))

def CROSS_ENTROPY(p,q) : 
   return np.sum(-p * np.log(q))

def KL_DIVERGENCE(p,q) : 
    return np.sum(-p * np.log(q/p))



ARRAY1 = np.array([35,36,45,95,24,15,6])
ARRAY1d = ARRAY1/np.sum(ARRAY1)
print(ARRAY1d)

ARRAY2 = np.array([20,56,85,52,22,20,1])
ARRAY2d = ARRAY2/np.sum(ARRAY2)
print(ARRAY2d)

# the ENTROPY of ARRAY1 
ENTROPY_e(ARRAY1d)

# the ENTROPY of ARRAY2
ENTROPY_e(ARRAY2d)

# the CROSS ENTROPY of ARRAY1 distribution wrt ARRAY2 distribution : 
ARRAY1_wrt_ARRAY2 = CROSS_ENTROPY(ARRAY1d, ARRAY2d)
print(ARRAY1_wrt_ARRAY2)

# the CROSS ENTROPY of ARRAY2 distribution wrt ARRAY1 distribution :
ARRAY2_wrt_ARRAY1 = CROSS_ENTROPY(ARRAY2d, ARRAY1d)
print(ARRAY2_wrt_ARRAY1)

# 3 ways to compute the KL divergence of ARRAY1 wrt ARRAY2

ARRAY1_KL_divergence_wrt_ARRAY2 = KL_DIVERGENCE(ARRAY1d, ARRAY2d)
print(ARRAY1_KL_divergence_wrt_ARRAY2)

ARRAY1_KL_divergence_wrt_ARRAY2a = ARRAY1_wrt_ARRAY2 - ENTROPY_e(ARRAY1d)
print(ARRAY1_KL_divergence_wrt_ARRAY2a)

ARRAY1_KL_divergence_wrt_ARRAY2b = np.sum(sp.special.rel_entr(ARRAY1d, ARRAY2d))
print(ARRAY1_KL_divergence_wrt_ARRAY2b)

# 3 ways to compute the KL divergence of ARRAY2 wrt ARRAY1

ARRAY2_KL_divergence_wrt_ARRAY1 = KL_DIVERGENCE(ARRAY2d, ARRAY1d)
print(ARRAY2_KL_divergence_wrt_ARRAY1)

ARRAY2_KL_divergence_wrt_ARRAY1a = ARRAY2_wrt_ARRAY1 - ENTROPY_e(ARRAY2d)
print(ARRAY2_KL_divergence_wrt_ARRAY1a)

ARRAY2_KL_divergence_wrt_ARRAY1b = np.sum(sp.special.rel_entr(ARRAY2d, ARRAY1d))
print(ARRAY2_KL_divergence_wrt_ARRAY1b)

